### ISSUE TITLE
WSL absolute path support?

### ISSUE THREAD

**Issue by ntucker** [microsoft/deoptexplorer-vscode#26]
Context: This is a follow up to https://github.com/microsoft/deoptexplorer-vscode/issues/12

To make my sourcemaps work correctly, I had them specify absolute paths. For example: /home/ntucker/src/rest-hooks/packages/normalizr/src/denormalize/unvisit.ts

I validated that this is a real path as I can open it in VScode just fine. However, when I click on that exact path from the 'deoptimization report' it tells me "The editor could not be opened because the file was not found."

Now this is a WSL2 system. I'm running VSCode through WSL though, so one would think the linux paths would be what it understands best.

I did notice one thing though: The path from 'deoptimization report' shows backslashes ('\') rather than forward slashes ('/'). This is even though when hovering on the link it shows forward slashes. Perhaps part of this extension code rewrites them to forward slashes, which is a bad assumption given people run VSCode through WSL?

**Comment by rbuckton** [comment]
It looks like this is due to how VS Code handles files when running in a remote session (such as via WSL, SSH, or in a Dev container). Rather than `file:` URLs, VS Code instead uses is own `vscode-remote:` URL format, and treats `file:` URLs somewhat differently.

Is it just the report that isn't working? I've been considering removing that feature as it is a bit out of date.

**Comment by ntucker** [comment]
It isn't working. It does seem nice to be able to open files through this part of the interface
